### ISSUE TITLE
 Atualização de Certificado *Comunicado Importante*

### ISSUE THREAD

**Issue by greguly** [leobaiano/WC-MaxiPago#1]
Prezado cliente,

        _*No dia 15/12/2016*_ a maxiPago! realizará a atualização do
        certificado de validade estendida em toda sua plataforma.
        Essa atualização é necessária e não pode ser adiada. Com o
        certificado de validade estendida devidamente instalado, todos
        os dados enviados entre seu site e a maxiPago! permanecem
        criptografados, mantendo a conexão confiável e segura.

        Veja abaixo como instalar o Certificado de Validade Estendida:
        1º Acesse a URL:
        http://www.maxipago.com/certificado/api_maxipago_net.crt
        <http://maxipago.us6.list-manage.com/track/click?u=a499e5a2b5ee0bfe771bea962&id=7a6b46d5a3&e=c28e0110fc>
        2º Faça download do arquivo: “api_maxipago_net.crt”
        3º Instale o arquivo em seu servidor para garantir a comunicação.

        Em caso de dúvida, por favor, entre em contato com o seu
        desenvolver ou suporte técnico de sua plataforma.

        Você também pode entrar em contato com o nosso suporte através
        de um dos canais abaixo:

        Telefone: (11) 2121-8536 ou E-mail: suporte@maxipago.com

**Comment by greguly** [comment]
:-)

**Comment by leobaiano** [comment]
Valeu @greguly!

Você utiliza o serviço deles?

**Comment by greguly** [comment]
Não uso mais ;-)

Mas eles tem meu email e ficam me enviando coisas de vez em quando.....

**Comment by leobaiano** [comment]
Valeu, muito obrigado por compartilhar o comunicado.
